name: Reusable CI (Build + Test)

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      java_version:
        required: false
        type: string
        default: "21"
      run_tests:
        required: false
        type: boolean
        default: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java_version }}

      - name: Build
        run: |
          if [ -f "mvnw" ]; then
            chmod +x mvnw
            ./mvnw -B -DskipTests package
          else
            mvn -B -DskipTests package
          fi

      - name: Test
        if: ${{ inputs.run_tests }}
        run: |
          if [ -f "mvnw" ]; then
            ./mvnw -B test
          else
            mvn -B test
          fi

          
      - name: Build Docker image 
        run: | 
          docker build -t ${{ inputs.image_name }}:${{ github.sha }} .

          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-build-artifact
          path: target/*.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag ${{ inputs.image_name }}:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ github.sha }}
          docker tag ${{ inputs.image_name }}:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:latest

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Snyk Container Scan (CLI)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk container test ${{ inputs.image_name }}:${{ github.sha }} \
            --severity-threshold=high \
            --file=Dockerfile \
            --json > snyk-results.json || true

          # Fail the job only if HIGH/CRITICAL vulnerabilities exist
          if grep -q '"severity":"high"\|"severity":"critical"' snyk-results.json; then
            echo "High/Critical vulnerabilities found"
            exit 1
          fi

          echo "No High/Critical vulnerabilities found"
          
          

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:latest

      - name: Cleanup
        if: always()
        run: |
          docker image prune -af || true
